In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Implement Mean Absolute Error


In [9]:
def mae(y_true,y_predicted):
    total_error = 0
    for y_t,y_p in zip(y_true,y_predicted):
        total_error += abs(y_t - y_p)
    print("Total Error: ", total_error)

    MAE = total_error/len(y_true)
    print("Mean Absolute Error: ", MAE)
    return MAE

In [10]:
mae(y_true,y_predicted)

Total Error:  2.5
Mean Absolute Error:  0.5


0.5

# Implementing same using numpy

In [16]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [17]:
np.mean(np.abs(y_predicted-y_true))

0.5

# Implement Log Loss or Binary Cross Entropy

In [18]:
np.log([0])

C:\Users\Admin\AppData\Local\Temp\ipykernel_16524\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [19]:
epsilon = 1e-15

In [22]:
np.log([1e-15])

array([-34.53877639])

In [23]:
y_predicted

array([1, 1, 0, 0, 1])

In [24]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [25]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

**we did the above step because log(0) is undefined**

In [26]:
y_predicted_new = np.array(y_predicted_new)

In [27]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [29]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new)) # log loss function formula

17.2696280766844

In [30]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [31]:
log_loss(y_true, y_predicted)

17.2696280766844