In [1]:
import numpy as np

In [2]:
x = [ [1,5,3] , [2,7,2] , [3,8,1]] 

In [3]:
x = np.array(x)

In [4]:
x

array([[1, 5, 3],
       [2, 7, 2],
       [3, 8, 1]])

In [5]:
x.sum(axis = 0)

array([ 6, 20,  6])

In [6]:
x.sum(axis = 1)

array([ 9, 11, 12])

In [7]:
x.ndim

2

In [8]:
x.flat

In [10]:
for i in x.flat:
    print(i)

1
5
3
2
7
2
3
8
1


In [11]:
x.nbytes

36

In [12]:
x.argmin()

0

In [13]:
x.argmax()

7

In [14]:
x = [ [1,5,3] , [2,7,2] , [3,8,1]] 

In [15]:
x = np.array(x)

In [16]:
x

array([[1, 5, 3],
       [2, 7, 2],
       [3, 8, 1]])

In [17]:
x.argmax()

7

In [18]:
x.argmin()

0

In [19]:
x.argmax(axis = 0)

array([2, 2, 0], dtype=int64)

In [20]:
x.argmin(axis = 1)

array([0, 0, 2], dtype=int64)

In [21]:
x.argmax(axis = 1)

array([1, 1, 1], dtype=int64)