In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,3,4] , [7,5,0] , [5,2,7]])

In [4]:
arr2 = np.array([[4,3,5] , [2,8,4] , [9,3,7]])

In [5]:
arr1

array([[1, 3, 4],
       [7, 5, 0],
       [5, 2, 7]])

In [6]:
arr2

array([[4, 3, 5],
       [2, 8, 4],
       [9, 3, 7]])

In [7]:
arr1 + arr2

array([[ 5,  6,  9],
       [ 9, 13,  4],
       [14,  5, 14]])

In [8]:
arr1 * arr2

array([[ 4,  9, 20],
       [14, 40,  0],
       [45,  6, 49]])

In [9]:
arr1 * arr2

array([[ 4,  9, 20],
       [14, 40,  0],
       [45,  6, 49]])

In [10]:
arr1 / arr2

array([[0.25      , 1.        , 0.8       ],
       [3.5       , 0.625     , 0.        ],
       [0.55555556, 0.66666667, 1.        ]])

In [11]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 2.        ],
       [2.64575131, 2.23606798, 0.        ],
       [2.23606798, 1.41421356, 2.64575131]])

In [12]:
arr1.max()

7

In [13]:
arr1.min()

0

In [24]:
np.where(arr1>5)

(array([1, 2], dtype=int64), array([0, 2], dtype=int64))

In [25]:
arr1

array([[1, 3, 4],
       [7, 5, 0],
       [5, 2, 7]])