In [1]:
import numpy as np

In [2]:
myArr = np.array([4,6,2,9,7])

In [3]:
myArr

array([4, 6, 2, 9, 7])

In [4]:
myArr = np.array([4,6,2,9,7], np.int64)

In [5]:
myArr

array([4, 6, 2, 9, 7], dtype=int64)

In [6]:
myArr = np.array([ [4,6,2,9,7] , [5,3,7,2,9] ], np.int64) 

In [7]:
myArr[1,3]

2

In [8]:
myArr.shape

(2, 5)

In [9]:
myArr.dtype

dtype('int64')

In [10]:
myArr[1,4] = 10

In [11]:
myArr

array([[ 4,  6,  2,  9,  7],
       [ 5,  3,  7,  2, 10]], dtype=int64)

# Different types of array creation

**1.Conversion from other Python strutures (e.g.,lists, tuples)**

In [12]:
arr = np.array([ [1,2,3,4,5] , [6,7,8,9,0] ])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

**2.Intrinsic numPy array creation objects (e.g., arange, ones, zeros)**

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
range = np.arange(10)

In [17]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ones = np.ones((2,7))

In [19]:
ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [20]:
lspace = np.linspace(1,4,10)

In [21]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [22]:
ide = np.identity(5)

In [23]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
ide.shape

(5, 5)

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr.ravel

<function ndarray.ravel>

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])